
language: java
jdk: oraclejdk11
deploy:
  provider: heroku
  api_key:
    secure: Bhv557Dw3IrlOuEHIln9HyvCu6VgGFhSldQRr4tvS0l+qtlUR/fKjXoWCrOyG1ikidVl/LYyTyChn350FerZuvW2PQFoOA2cp/dHxgytTvl1WWRE+s1SFZZFnrJ23t2Ny3LuqsTkogLYnwCrys9ad9gFh4nc4RZ+7irICQqi68H7jknBEYDUmo8AsRiO6LPnno0HWQgHEgAdz3FYROE9agnd5EQZSfs1Lg4u8JSnoJQOXY50UD0iu54WrIuIKTjjGoMM9NHpWyxu8mjkPot5HLvVMzs8FILfNcbYwa8HAzC2RGLk8DFeCiS7I8OEveixTgGkJd6GQIZ48JHGioJHeNyxBZCYHpyjMytw//cazaGxkNzKCPnM3yWKyT0WPf75RIwkA+StAH/z7NDMMSQoKoTvYFwQ1CddKFx/+04XSfLl6IUMtd1XkNNhFxAzBAhpr2G6fBT13sZjRWHphNe9T2R8uMaL5mS17oQ3fmpvSNIR0QpmbHivs73XAsq8v5SO4gM9I3/rNTUSxOwBiu/uEPTHTtE63pnF0oINgPx+OVDdIFbrrTj+nsZFUEuK1Pot6d11NYVyQ2TU95Q6vV8l+SFhKTCJap5EthxT8ZILhnfHL/+czzu52/vT3iiVfHA7KRoM0AsdPEM2bobFys0wafZwCoVVRalClMJ38L8wuPk=
    app: se452-g6
