language: java
jdk: oraclejdk11
deploy:
  provider: heroku
  api_key:
    secure: BoUmOoYhLwTeabDXllFIgdUu8HLd49AoOvQepKmX0nmJGn9sslhJ7rXnWNIWJDr46gUwMOZ6Lu5uVgX0IZ97k+sgN7YX7g4aWcjbmuZprG8c5dE4SvGD2LZRFnRagMeKSTYzhZg72jSLh/xwXeugjC3qIDU7Qy0mOA16DgBHz672eXpw2Ujq9c/TY5xd6SlgRpBQlsysdxVrSkdJ9DJ24OPeWHCgR7lFlB3ckOzfAnwyz5NYhvJqAP4tuL/3/ATGkHszffOuYnXmSCqsrksUmDTrO66FHQe4mcnJI/q2NVqqxBaL0lLy1Rg5x89IHCeWnUsM9GDnTU4h8mXe2RIROEJrSAdnQhkOOVUABmpBYh7vuRQWv6L9V6CMD3vSjTWluA9cna/xE/u0UgfQl7l9bFfNOj066KMA3jgi3UQLJeOAx0KGAqCVosKu/D3iJ4j9iaYkOfquSWqX4Su7LB9d7MEZftrfrROvGuW4LHHnkGshvcVI8lD82M6MtDojD2g0HuElw4HDiQ5riDIIETR+xR0jiNJpsHDFMqY8pBiXrXA5ip8gmgbv2o2xgslwcTVYlLj3ipyeB0ONYlu7nvJAzxocT+QPg4on3xy9+F0bxsEq0waC7gpVX6EALH2Dn2EPwv0+VwhaRNUBZ10B0F0Csf3yk5bMTFh2FWEm6ezU3fs=
    app: g6utilities
