language: java
jdk: oraclejdk11
deploy:
  provider: heroku
  api_key:
    secure: y9r8sYV0V1yzQPYmYWV40FbwLiTrBcUR3lC8x1BL4EcwZLiy1VraTjmDdUqe2bQzNdv35cs4UqmWj9zeqTKTfADb6/SHhEe0KU066MklDQbOElYAZEQnRpC6l126OZ39hSqo6dkViouMHO/Fm1MFeiSPYFDisG5HuOJKJAOIP3iohJ7FUhyWk4wW9twvLahNR8CWk2ky/wulYXvGFz/PX2Ome+ahocFVjESI9FOL9IUOgpyJdsCjE5lQZrzngH10chd1f41agyBPXzCSLpBp0XG5WbzlJ8ogE29HSjpXtvKUoJj5q7E42Za5f/bPwWnMvL3UDRMIYcoK//w0AsHaTfiwuynjN14YLIZGMaaog9pUokq2GWmVs/3ck/ZzYYuSIrSNG94TB5VRH9RDbMHjwLZ5PA1a7sT4m+P3p5G83WeF5WaM57/ZwFd/THQGBtUiqbPwGQsEPEhz14eUBTE3YTqmrTkV9EkaD7aD4E/fFUMgSFwl6ztKEjXmBagSAVS2bBTQSDjhgoUndOPAoaXSiKkNqtsN0OmDGoUWuIyc9ary6r2UX5HhRPyLNtFwk737T+pz3k+T5Vvu4zl/tvT3XnXEGjrFXSphqlgAgqw6UeEs8ssDzJGnl7q24DOS/xR6Ka6Q4UII+HlUuxtJ+/Kyj3cg3u3khf71l3fIYZsk6zY=
    app: g6utilities
